let f=0; const ok=(c,m)=>{ if(!c){f++;console.log("FALLA:",m)} else console.log("ok:",m) };
lset("fase",2);
ok(chequearRecord("press_banca",{kg:10,reps:12})===false,"primera serie no es record");
ok(chequearRecord("press_banca",{kg:10,reps:13})===true,"10x13 supera 10x12");
ok(chequearRecord("dominada",{kg:0,reps:5})===false,"dominada linea base");
ok(chequearRecord("dominada",{kg:0,reps:6})===true,"dominada record por reps");
ok(chequearRecord("plancha",{seg:30})===false,"plancha linea base");
ok(chequearRecord("plancha",{seg:35})===true,"plancha record por tiempo");
setRonda("B","goblet",0,{kg:16,reps:20}); setRonda("B","goblet",1,{kg:16,reps:20}); setRonda("B","goblet",2,{kg:16,reps:20});
setRonda("B","plancha",0,{seg:30});
setRonda("D","rdl",0,{kg:12,reps:12}); setRonda("D","rdl",1,{kg:12,reps:11});
["press_banca","remo_inclinado"].forEach(k=>{setRonda("A",k,0,{kg:10,reps:10});setRonda("A",k,1,{kg:10,reps:10})});
setRonda("A","press_hombro",0,{kg:8,reps:10}); setRonda("A","press_hombro",1,{kg:8,reps:10});
setRonda("A","dominada",0,{kg:0,reps:4});
cambiarSemana(1);
ok(ultimaVez("B","goblet")?.w===1,"ultimaVez encuentra la semana 1");
lset("fase",3);
const u=ultimaVez("B","goblet_talones");
ok(u&&u.k==="goblet","fase 3: la variante hereda el historial");
lset("fase",2);
ok(textoObjetivo("D",sesionDe("D").b1[0],"rdl").includes("20 reps"),"objetivo al techo");
ok(textoObjetivo("B",sesionDe("B").b2[0],"goblet").includes("Techo alcanzado"),"techo alcanzado");
ok(textoObjetivo("B",sesionDe("B").b2[1],"plancha").includes("35 s"),"tiempo: mejor mas 5");
ok(textoObjetivo("A",sesionDe("A").b2[1],"dominada").includes("mejor ronda"),"dominadas con historial");
lset("fase",1);
terminarSesionDe(1,"A",true);
const d=sesionHecha(1,"A");
ok(d&&d.seriesTotales===7,"seriesTotales 7, fue "+d?.seriesTotales);
ok(d.rondasCompletadas===3,"rondas completas 3, fue "+d.rondasCompletadas);
ok(d.tonelaje===560,"tonelaje 560, fue "+d.tonelaje);
ok(d.cierreOmitido===true,"cierreOmitido");
ok(!!lget("logros",{}).arranque,"logro arranque");
const antes=JSON.stringify(d); terminarSesionDe(1,"A",true);
ok(JSON.stringify(sesionHecha(1,"A"))===antes,"no se termina dos veces");
Object.keys(store).filter(k=>/^fz_sesion_\d/.test(k)).forEach(k=>delete store[k]);
const dia=n=>new Date(Date.now()-n*86400000).toISOString();
lset("sesion_1_A",{fecha:dia(20)}); lset("sesion_1_B",{fecha:dia(18)}); lset("sesion_1_C",{fecha:dia(16)});
ok(calcRacha().n===3,"racha 3");
lset("sesion_2_A",{fecha:dia(12)}); ok(calcRacha().n===4,"salto recuperado en 10 dias mantiene la racha");
lset("sesion_2_A",{fecha:dia(2)});  ok(calcRacha().n===1,"salto recuperado tarde reinicia");
lset("sesion_3_A",{fecha:dia(1)});  ok(calcRacha().n===1,"dos huecos reinician");
ok(curvaHTML("goblet").includes("circle"),"curva con puntos");
ok(listaEjHTML().split('class="tarjeta"').length-1===40,"buscador vacio lista los 40");
filtroEj="espalda"; ok(listaEjHTML().includes("Remo"),"buscar espalda encuentra los remos");
filtroEj="";
console.log(f? "\n*** "+f+" FALLAS ***":"\nlogica: todo verde");
process.exit(f?1:0);
